package com.example.browser.utils

enum class AppLanguage(val displayName: String, val code: String) {
    EN("English", "en"),
    ES("Español", "es"),
    FR("Français", "fr"),
    DE("Deutsch", "de"),
    JA("日本語", "ja"),
    PT("Português", "pt"),
    IT("Italiano", "it")
}

object LanguageManager {
    private val translations = mapOf(
        AppLanguage.EN to mapOf(
            "app_welcome" to "Welcome to AuryxBrowser",
            "app_tagline" to "Privacy. Extreme Performance. Integrated Utility.",
            "intro_p1_title" to "Advanced Privacy Engine",
            "intro_p1_desc" to "Safeguard your data with extreme privacy modes, native secure local password vaults, and built-in ad blockers.",
            "intro_p2_title" to "Performance Fueling",
            "intro_p2_desc" to "Toggle through Balanced, Boost, and EXtreme modes to customize rendering engine speed, UI refresh rate, and power savings.",
            "intro_p3_title" to "AuryxTools Utilities",
            "intro_p3_desc" to "Access 5 integrated developer and user utilities right in your pocket: scratchpad, speed test, QR maker, and source inspector.",
            "btn_accept" to "Accept & Launch",
            "search_hint" to "Search or enter address...",
            "nav_back" to "Back",
            "nav_forward" to "Forward",
            "nav_tabs" to "Tabs",
            "nav_bookmarks" to "Bookmarks",
            "nav_history" to "History",
            "nav_settings" to "Settings",
            "nav_tools" to "AuryxTools",
            "sync_title" to "Cross-Device Sync",
            "sync_desc" to "Sync passwords, tabs, and bookmarks seamlessly with securely encrypted accounts.",
            "sync_unlocked" to "Securely Sycned",
            "btn_sync" to "Account Sync Status",
            "perf_title" to "Performance Tuning",
            "pref_balanced" to "Balanced Mode (Optimized battery life)",
            "pref_boost" to "Boost Mode (High rendering engine speed)",
            "pref_extreme" to "EXtreme Mode (Max FPS & instant reaction)",
            "pwd_manager" to "Secure Password Vault",
            "pwd_add" to "Store Password",
            "pwd_vault_empty" to "Vault empty. Use this space to securely save credentials locally.",
            "adblock_title" to "Auryx Ad Block",
            "adblock_desc" to "Toggle filter to intercept unsecure trackers and overlay advertisements.",
            "adblock_counter" to "Total blocked elements this session",
            "btn_clear_data" to "Purge Cache & Browsing Data",
            "cache_cleared" to "Temporary data, cookies, and cache cleared!",
            "reading_mode" to "Aura Reading Mode",
            "reading_mode_desc" to "Optimized content screen containing simplified text fonts for reading under low CPU/low memory states.",
            "tab_manager" to "Tab Management",
            "btn_new_tab" to "Add New Tab",
            "sys_stats" to "Device & Framework Diagnostics",
            "tool_scratch" to "Scratchpad",
            "tool_speed" to "Web Speed Gauge",
            "tool_pwd_gen" to "Password Generator",
            "tool_qr" to "QR Shield Maker",
            "tool_inspector" to "Developer Inspector",
            "btn_save" to "Save",
            "btn_close" to "Close",
            "btn_delete" to "Delete",
            "btn_clear" to "Clear",
            "lang_select" to "Interface Language",
            "privacy_on" to "Privacy Shield ON (Hidden IP, anti-tracker active)",
            "privacy_off" to "Normal Privacy (Standard Web protocols)"
        ),
        AppLanguage.ES to mapOf(
            "app_welcome" to "Bienvenido a AuryxBrowser",
            "app_tagline" to "Privacidad. Rendimiento Extremo. Utilidad Integrada.",
            "intro_p1_title" to "Motor de Privacidad Avanzado",
            "intro_p1_desc" to "Proteja sus datos con modos de privacidad extrema, bóveda local segura de contraseñas y bloqueadores de anuncios.",
            "intro_p2_title" to "Aceleración de Rendimiento",
            "intro_p2_desc" to "Alterna entre los modos Equilibrado, Boost y EXtreme para personalizar la velocidad de renderizado, FPS y ahorro de energía.",
            "intro_p3_title" to "Utilidades AuryxTools",
            "intro_p3_desc" to "Acceda a 5 herramientas integradas de desarrollo y productividad: bloc de notas, prueba de velocidad, creador de QR e inspector de código.",
            "btn_accept" to "Aceptar y Lanzar",
            "search_hint" to "Buscar o ingresar link...",
            "nav_back" to "Atrás",
            "nav_forward" to "Adelante",
            "nav_tabs" to "Pestañas",
            "nav_bookmarks" to "Marcadores",
            "nav_history" to "Historial",
            "nav_settings" to "Ajustes",
            "nav_tools" to "AuryxTools",
            "sync_title" to "Sincronización Multidispositivo",
            "sync_desc" to "Sincronice contraseñas, pestañas y marcadores de manera segura con cuentas cifradas.",
            "sync_unlocked" to "Sincronizado Seguro",
            "btn_sync" to "Estado de Sincronización",
            "perf_title" to "Ajustes de Rendimiento",
            "pref_balanced" to "Modo Equilibrado (Batería optimizada)",
            "pref_boost" to "Modo Boost (Alta velocidad de carga)",
            "pref_extreme" to "Modo EXtreme (Máximos FPS y respuesta instantánea)",
            "pwd_manager" to "Bóveda de Contraseñas",
            "pwd_add" to "Guardar Contraseña",
            "pwd_vault_empty" to "Bóveda vacía. Almacene credenciales localmente con seguridad.",
            "adblock_title" to "Bloqueador de Anuncios Auryx",
            "adblock_desc" to "Activa el filtro para interceptar rastreadores publicitarios dañinos.",
            "adblock_counter" to "Anuncios y rastreadores bloqueados esta sesión",
            "btn_clear_data" to "Purgar Caché y Datos Temporales",
            "cache_cleared" to "¡Caché, historial y rastreadores eliminados!",
            "reading_mode" to "Modo de Lectura Aura",
            "reading_mode_desc" to "Optimizado para dispositivos sencillos, muestra solo texto legible sin consumir CPU.",
            "tab_manager" to "Gestor de Pestañas",
            "btn_new_tab" to "Nueva Pestaña",
            "sys_stats" to "Diagnósticos del Dispositivo y Sistema",
            "tool_scratch" to "Bloc de Notas",
            "tool_speed" to "Prueba de Velocidad",
            "tool_pwd_gen" to "Generador de Claves",
            "tool_qr" to "Creador de Códigos QR",
            "tool_inspector" to "Inspector Web",
            "btn_save" to "Guardar",
            "btn_close" to "Cerrar",
            "btn_delete" to "Eliminar",
            "btn_clear" to "Limpiar",
            "lang_select" to "Idioma de Interfaz",
            "privacy_on" to "Escudo de Privacidad ACTIVO (IP oculta, anti-rastreo)",
            "privacy_off" to "Privacidad Normal (Protocolos estándar)"
        ),
        AppLanguage.FR to mapOf(
            "app_welcome" to "Bienvenue sur AuryxBrowser",
            "app_tagline" to "Confidentialité. Performance Extrême. Utilitaires.",
            "intro_p1_title" to "Moteur de Confidentialité",
            "intro_p1_desc" to "Protégez vos données avec des modes de confidentialité absolue, un coffre-fort local et des bloqueurs de pubs.",
            "intro_p2_title" to "Performances Redessinées",
            "intro_p2_desc" to "Basculez entre les modes Équilibré, Boost et EXtreme pour ajuster le moteur de rendu, les FPS et la batterie.",
            "intro_p3_title" to "Utilitaires AuryxTools",
            "intro_p3_desc" to "Accédez à 5 utilitaires intégrés directement : bloc-notes, test de vitesse, créateur de QR et inspecteur web.",
            "btn_accept" to "Accepter & Lancer",
            "search_hint" to "Rechercher ou saisir adresse...",
            "nav_back" to "Retour",
            "nav_forward" to "Suivant",
            "nav_tabs" to "Onglets",
            "nav_bookmarks" to "Favoris",
            "nav_history" to "Historique",
            "nav_settings" to "Paramètres",
            "nav_tools" to "AuryxTools",
            "sync_title" to "Synchronisation Multi-appareil",
            "sync_desc" to "Synchronisez vos favoris, onglets et identifiants en toute sécurité.",
            "sync_unlocked" to "Synchronisation Sécurisée",
            "btn_sync" to "Statut Compte Sync",
            "perf_title" to "Optimisation Performance",
            "pref_balanced" to "Mode Équilibré (Batterie préservée)",
            "pref_boost" to "Mode Boost (Rendu accéléré)",
            "pref_extreme" to "Mode EXtreme (FPS maximum, instantané)",
            "pwd_manager" to "Coffre-fort Mots de Passe",
            "pwd_add" to "Ajouter un mot de passe",
            "pwd_vault_empty" to "Coffre vide. Enregistrez vos identifiants localement.",
            "adblock_title" to "Bloqueur Auryx Ad",
            "adblock_desc" to "Interceptez les publicités agressives et les scripts de suivi.",
            "adblock_counter" to "Éléments publicitaires bloqués",
            "btn_clear_data" to "Purger le Cache et Historique",
            "cache_cleared" to "Données temporaires nettoyées avec succès !",
            "reading_mode" to "Mode Lecture Simplifiée",
            "reading_mode_desc" to "Version d'affichage minimale sans fioritures pour réduire la charge CPU.",
            "tab_manager" to "Gestionnaire d'Onglets",
            "btn_new_tab" to "Nouvel Onglet",
            "sys_stats" to "Diagnostics Matériel et Système",
            "tool_scratch" to "Bloc-notes Rapide",
            "tool_speed" to "Test d'Débit Web",
            "tool_pwd_gen" to "Générateur de Clés",
            "tool_qr" to "Générateur de QR Code",
            "tool_inspector" to "Inspecteur de Code",
            "btn_save" to "Enregistrer",
            "btn_close" to "Fermer",
            "btn_delete" to "Supprimer",
            "btn_clear" to "Vider",
            "lang_select" to "Langue de l'interface",
            "privacy_on" to "Bouclier de Confidentialité Activé",
            "privacy_off" to "Confidentialité Standard"
        ),
        AppLanguage.DE to mapOf(
            "app_welcome" to "Willkommen bei AuryxBrowser",
            "app_tagline" to "Datenschutz. Extreme Leistung. Werkzeuge.",
            "intro_p1_title" to "Datenschutz-Engine",
            "intro_p1_desc" to "Sichern Sie Ihre Daten mit extremen Datenschutzmodi, lokalem Passworttresor und Werbeblocker.",
            "intro_p2_title" to "Leistungsstufen",
            "intro_p2_desc" to "Wechseln Sie zwischen Balanced, Boost und EXtreme, um Bildrate, Rendergeschwindigkeit und Akku zu tunen.",
            "intro_p3_title" to "AuryxTools Utilities",
            "intro_p3_desc" to "5 Hilfsprogramme direkt integriert: Notizblock, Speed-Test, QR-Ersteller und Quellcode-Inspektor.",
            "btn_accept" to "Akzeptieren & Starten",
            "search_hint" to "Suchen oder Link eingeben...",
            "nav_back" to "Zurück",
            "nav_forward" to "Vorwärts",
            "nav_tabs" to "Tabs",
            "nav_bookmarks" to "Lesezeichen",
            "nav_history" to "Verlauf",
            "nav_settings" to "Einstellungen",
            "nav_tools" to "AuryxTools",
            "sync_title" to "Geräteübergreifende Sync",
            "sync_desc" to "Lesezeichen, Tabs und Zugangsdaten sicher mit Verschlüsselung synchronisieren.",
            "sync_unlocked" to "Verschlüsselt Synchronisiert",
            "btn_sync" to "Synchronisationsstatus",
            "perf_title" to "Leistungseinstellungen",
            "pref_balanced" to "Ausgeglichener Modus (Akkuschonend)",
            "pref_boost" to "Boost-Modus (Schnelles Laden & Renderspeed)",
            "pref_extreme" to "EXtreme-Modus (Maximaler FPS-Durchsatz)",
            "pwd_manager" to "Sicherer Passwort-Tresor",
            "pwd_add" to "Passwort speichern",
            "pwd_vault_empty" to "Der Tresor ist leer. Speichern Sie Logindaten verschlüsselt.",
            "adblock_title" to "Auryx Werbeblocker",
            "adblock_desc" to "Werbungen, Popups und schädliche Datensammler zuverlässig sperren.",
            "adblock_counter" to "Blockierte Tracker & Skripte",
            "btn_clear_data" to "Browserdaten & Cache leeren",
            "cache_cleared" to "Browserdaten, Cookies und Cache gelöscht!",
            "reading_mode" to "Aura Lesemodus",
            "reading_mode_desc" to "Minimalistische Textversion für eine flüssige Darstellung auf schwächeren Handys.",
            "tab_manager" to "Tab-Verwaltung",
            "btn_new_tab" to "Neuer Tab",
            "sys_stats" to "Geräte- und Hardwarediagnose",
            "tool_scratch" to "Notizen",
            "tool_speed" to "Geschwindigkeits-Uhr",
            "tool_pwd_gen" to "Generatorkennwort",
            "tool_qr" to "QR-Code-Ersteller",
            "tool_inspector" to "Web-Inspektor",
            "btn_save" to "Speichern",
            "btn_close" to "Schließen",
            "btn_delete" to "Löschen",
            "btn_clear" to "Leeren",
            "lang_select" to "Oberflächensprache",
            "privacy_on" to "Datenschutz-Schutzschild AKTIV (Simulierter VPN)",
            "privacy_off" to "Normaler Datenschutz"
        ),
        AppLanguage.JA to mapOf(
            "app_welcome" to "AuryxBrowserへようこそ",
            "app_tagline" to "プライバシー。極限のパフォーマンス。多彩なユーティリティ。",
            "intro_p1_title" to "高度なプライバシー保護",
            "intro_p1_desc" to "極限プライバシーモード、安全なローカル暗号化パスワード保管庫、および広告ブロッカーでデータを保護します。",
            "intro_p2_title" to "パフォーマンス調整",
            "intro_p2_desc" to "Balanced、Boost、EXtremeの各モードを切り替えて、描画エンジン速度、最大FPS、省電力設定をチューニング可能。",
            "intro_p3_title" to "AuryxTools ユーティリティ",
            "intro_p3_desc" to "メモ帳、超ビジュアル速度テスト、QRコード生成、開発者用WEBインスペクターを含む5つ便利ツールを内蔵。",
            "btn_accept" to "承諾して起動する",
            "search_hint" to "検索ワードまたはアドレスを入力...",
            "nav_back" to "戻る",
            "nav_forward" to "進む",
            "nav_tabs" to "タブ",
            "nav_bookmarks" to "ブックマーク",
            "nav_history" to "履歴",
            "nav_settings" to "設定",
            "nav_tools" to "AuryxTools",
            "sync_title" to "複数端末間の同期",
            "sync_desc" to "暗号化アカウントで、ブックマークやパスワード、開いているタブを自動同期。",
            "sync_unlocked" to "完全に同期済み",
            "btn_sync" to "同期アカウント状態",
            "perf_title" to "パフォーマンス制御設定",
            "pref_balanced" to "Balanced モード（最適なバッテリー稼働）",
            "pref_boost" to "Boost モード（高速ダウンロードと描画）",
            "pref_extreme" to "EXtreme モード（超高FPSと瞬時応答）",
            "pwd_manager" to "安全なパスワード保管庫",
            "pwd_add" to "パスワードを保存する",
            "pwd_vault_empty" to "保管庫は空です。ログインアカウントを暗号化してローカル保存します。",
            "adblock_title" to "Auryx広告ブロッカー",
            "adblock_desc" to "煩わしい追跡スクリプトやポップアップなどを自動的に遮断します。",
            "adblock_counter" to "セッション中にブロックした広告・追跡の合計",
            "btn_clear_data" to "キャッシュと一時データのパージ",
            "cache_cleared" to "ブラウザのキャッシュ、履歴、Cookieなどを完全に消去しました。",
            "reading_mode" to "Aura リーディング・モード",
            "reading_mode_desc" to "低スペックデバイス向けに広告や無駄なCSSをカットした、読み物閲覧用テキスト画面です。",
            "tab_manager" to "タブマネージャー",
            "btn_new_tab" to "新規タブ追加",
            "sys_stats" to "端末スペックおよびOS診断",
            "tool_scratch" to "スクラッチパッド",
            "tool_speed" to "スピード測定器",
            "tool_pwd_gen" to "セキュリティパス作成",
            "tool_qr" to "QRコード生成器",
            "tool_inspector" to "WEBインスペクター",
            "btn_save" to "保存",
            "btn_close" to "閉じる",
            "btn_delete" to "削除",
            "btn_clear" to "クリア",
            "lang_select" to "インターフェース言語設定",
            "privacy_on" to "プライバシーシールド有効（非追跡・仮想IP）",
            "privacy_off" to "標準プライバシー"
        ),
        AppLanguage.PT to mapOf(
            "app_welcome" to "Bem-vindo ao AuryxBrowser",
            "app_tagline" to "Privacidade. Performance Extrema. Útil.",
            "intro_p1_title" to "Motor de Privacidade",
            "intro_p1_desc" to "Mantenha dados seguros com modos extremos, cofre de senhas blindado e bloqueador de anúncios nativo.",
            "intro_p2_title" to "Modos de Desempenho",
            "intro_p2_desc" to "Alternar entre Equilibrado, Boost e EXtreme para gerenciar renderização, consumo e taxa de quadros.",
            "intro_p3_title" to "Suíte AuryxTools",
            "intro_p3_desc" to "Tenha 5 microaplicativos completos incorporados: notas rápidas, velocímetro, segurança de chaves, QR e depurador de DOM.",
            "btn_accept" to "Aceitar & Iniciar",
            "search_hint" to "Pesquise ou digite a URL...",
            "nav_back" to "Voltar",
            "nav_forward" to "Avançar",
            "nav_tabs" to "Abas",
            "nav_bookmarks" to "Favoritos",
            "nav_history" to "Histórico",
            "nav_settings" to "Ajustes",
            "nav_tools" to "AuryxTools",
            "sync_title" to "Sincronização na Nuvem",
            "sync_desc" to "Conserve abas e credenciais salvas replicadas com criptografia ponto a ponto.",
            "sync_unlocked" to "Dispositivo Sincronizado",
            "btn_sync" to "Estado de Sincronização",
            "perf_title" to "Configurações de Engine",
            "pref_balanced" to "Modo Equilibrado (Ajuste para bateria)",
            "pref_boost" to "Modo Boost (Foco no carregamento ágil)",
            "pref_extreme" to "Modo EXtreme (Renderização total e zero latência)",
            "pwd_manager" to "Cofre de Credenciais",
            "pwd_add" to "Salvar Credencial",
            "pwd_vault_empty" to "Cofre vazio. Crie uma nova senha e armazene seguro.",
            "adblock_title" to "Bloqueador Nativo Auryx",
            "adblock_desc" to "Elimine rastreadores abusivos de redes para despoluir as páginas.",
            "adblock_counter" to "Métricas de elementos filtrados",
            "btn_clear_data" to "Limpar Armazenamento & Cache",
            "cache_cleared" to "Todos os cookies e cache local foram apagados!",
            "reading_mode" to "Modo de Leitura Minimalista",
            "reading_mode_desc" to "Foque no conteúdo sem elementos pesados e economize tempo de CPU.",
            "tab_manager" to "Gerenciamento de Abas",
            "btn_new_tab" to "Adicionar Aba",
            "sys_stats" to "Relatório Técnico do Dispositivo",
            "tool_scratch" to "Editor Rápido",
            "tool_speed" to "Velocímetro de Rede",
            "tool_pwd_gen" to "Gerador de Códigos",
            "tool_qr" to "Gerador de QR",
            "tool_inspector" to "Depurador Web",
            "btn_save" to "Guardar",
            "btn_close" to "Fechar",
            "btn_delete" to "Excluir",
            "btn_clear" to "Limpar",
            "lang_select" to "Idioma da Interface",
            "privacy_on" to "Blindagem ativa (IP ocultada, sem cookies de terceiros)",
            "privacy_off" to "Privacidade Padrão"
        ),
        AppLanguage.IT to mapOf(
            "app_welcome" to "Benvenuto in AuryxBrowser",
            "app_tagline" to "Privacy. Performance Estrema. Strumenti Integrati.",
            "intro_p1_title" to "Motore di Privacy Avanzato",
            "intro_p1_desc" to "Difendi la tua navigazione con impostazioni estreme, una cassaforte locale sicura per le password ed un ad blocker nativo.",
            "intro_p2_title" to "Regolazione Prestazioni",
            "intro_p2_desc" to "Seleziona Balanced, Boost, o EXtreme per configurare FPS, velocità del motore ed efficienza energetica.",
            "intro_p3_title" to "Suites AuryxTools",
            "intro_p3_desc" to "Accedi a 5 strumenti essenziali direttamente dal browser: blocco note, speed test grafico, QR code generator e inspect-code.",
            "btn_accept" to "Accetta & Avvia",
            "search_hint" to "Cerca o inserisci URL...",
            "nav_back" to "Indietro",
            "nav_forward" to "Avanti",
            "nav_tabs" to "Schede",
            "nav_bookmarks" to "Preferiti",
            "nav_history" to "Cronologia",
            "nav_settings" to "Impostazioni",
            "nav_tools" to "AuryxTools",
            "sync_title" to "Sincronizzazione Account",
            "sync_desc" to "Mantieni preferiti, password e schede sincronizzati via server protetto.",
            "sync_unlocked" to "Sincronizzato in Sicurezza",
            "btn_sync" to "Stato Navigazione Cloud",
            "perf_title" to "Gestione Framerate & Consumi",
            "pref_balanced" to "Modalità Balanced (Risparmio equilibrato)",
            "pref_boost" to "Modalità Boost (Caricamento super-veloce)",
            "pref_extreme" to "Modalità EXtreme (Massimo framerate e reattività)",
            "pwd_manager" to "Cassaforte Password Cifrata",
            "pwd_add" to "Memorizza Password",
            "pwd_vault_empty" to "Nessuna password salvata. Aggiungine una per tenerla al sicuro.",
            "adblock_title" to "Auryx Ad Block",
            "adblock_desc" to "Neutralizza inserzioni moleste e codici di profilazione.",
            "adblock_counter" to "Pubblicità e tracker bloccati finora",
            "btn_clear_data" to "Svuota Cache & File Temporanei",
            "cache_cleared" to "Donne temporanee, cronologia e cookie eliminati!",
            "reading_mode" to "Lettura Semplificata Aura",
            "reading_mode_desc" to "Interfaccia purificata che isola i contenuti testuali importanti riducendo al minimo l'uso di CPU.",
            "tab_manager" to "Organizzazione Schede",
            "btn_new_tab" to "Nuova Scheda",
            "sys_stats" to "Diagnostica Hardware e Framework",
            "tool_scratch" to "Taccuino Rapido",
            "tool_speed" to "Velocimetro Flash",
            "tool_pwd_gen" to "Generatore Codici",
            "tool_qr" to "Creatore Codici QR",
            "tool_inspector" to "Ispettore Elementi",
            "btn_save" to "Salva",
            "btn_close" to "Chiudi",
            "btn_delete" to "Elimina",
            "btn_clear" to "Inizializza",
            "lang_select" to "Lingua di Sistema",
            "privacy_on" to "Scudo Privacy ATTIVO (IP criptato, anti-profilazione)",
            "privacy_off" to "Privacy Comune"
        )
    )

    fun getString(key: String, lang: AppLanguage): String {
        return translations[lang]?.get(key) ?: translations[AppLanguage.EN]?.get(key) ?: "{$key}"
    }
}
